=== gagi3/XML-2020/poverenik/src/main/java/rs/pijz/server/poverenik/model/izvestaj/izvestaj.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:iz="http://www.pijz.rs/izvestaj"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
    targetNamespace="http://www.pijz.rs/izvestaj" elementFormDefault="qualified" vc:minVersion="1.1"
    xmlns:cmn="http://www.pijz.rs/common">

    <xs:import namespace="http://www.pijz.rs/common" schemaLocation="common.xsd"/>
    <xs:element name="Izvestaj" type="iz:Izvestaj"> </xs:element>
    <xs:complexType name="ZalbaSadrzaj">
        <xs:sequence>
            <xs:element name="zalbaID" type="xs:ID"/>
            <xs:element name="sadrzaj" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Izvestaj">
        <xs:sequence>
            <xs:element name="metadata" type="cmn:MetaData"/>
            <xs:element name="brojPodnetihZahteva" type="xs:int"/>
            <xs:element name="brojOdbijenihZahteva" type="xs:int"/>
            <xs:element name="brojZalbiOdluka" type="xs:int"/>
            <xs:element name="zalbe" type="iz:ZalbaSadrzaj"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID"/>
        <xs:attribute name="sluzbenikID" type="xs:string"/>
    </xs:complexType>
</xs:schema>

=== gagi3/XML-2020/data/xsd/sample/izvestaj1.xml
<?xml version="1.0" encoding="UTF-8"?>
<iz:Izvestaj xmlns:iz="http://www.pijz.rs/izvestaj"
 xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
 xmlns:cmn="http://www.pijz.rs/common"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.pijz.rs/izvestaj file:/D:/College/XML%202020/Project/XML-2020/data/xsd/izvestaj.xsd" id="ID000" sluzbenikID="sluzbenikID0">
    <iz:metadata>
        <cmn:meta property="property0" content="content0">meta0</cmn:meta>
        <cmn:meta property="property1" content="content1">meta1</cmn:meta>
        <cmn:meta property="property2" content="content2">meta2</cmn:meta>
    </iz:metadata>
    <iz:brojPodnetihZahteva>0</iz:brojPodnetihZahteva>
    <iz:brojOdbijenihZahteva>0</iz:brojOdbijenihZahteva>
    <iz:brojZalbiOdluka>0</iz:brojZalbiOdluka>
    <iz:zalbe>
        <iz:zalbaID>ID001</iz:zalbaID>
        <iz:sadrzaj>sadrzaj0</iz:sadrzaj>
    </iz:zalbe>
    <iz:zalbe>
        <iz:zalbaID>ID002</iz:zalbaID>
        <iz:sadrzaj>sadrzaj1</iz:sadrzaj>
    </iz:zalbe>
    <iz:zalbe>
        <iz:zalbaID>ID003</iz:zalbaID>
        <iz:sadrzaj>sadrzaj2</iz:sadrzaj>
    </iz:zalbe>
</iz:Izvestaj>

=== gagi3/XML-2020/data/xml/izvestaj.xml
<?xml version="1.0" encoding="UTF-8"?>
<iz:Izvestaj xmlns:iz="http://www.pijz.rs/izvestaj"
 xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
 xmlns:cmn="http://www.pijz.rs/common"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.pijz.rs/izvestaj file:/D:/College/XML%202020/Project/XML-2020/data/xsd/izvestaj.xsd" id="ID000" sluzbenikID="sluzbenikID0">
    <iz:metadata>
        <cmn:meta property="iz:brojZalbiOdluka" content="18"></cmn:meta>
    </iz:metadata>
    <iz:brojPodnetihZahteva>18</iz:brojPodnetihZahteva>
    <iz:brojOdbijenihZahteva>6</iz:brojOdbijenihZahteva>
    <iz:brojZalbiOdluka>10</iz:brojZalbiOdluka>
    <iz:zalbe>
        <iz:zalbaID>ID001</iz:zalbaID>
        <iz:sadrzaj>Садржај прве жалбе.</iz:sadrzaj>
    </iz:zalbe>
    <iz:zalbe>
        <iz:zalbaID>ID002</iz:zalbaID>
        <iz:sadrzaj>Садржај друге жалбе.</iz:sadrzaj>
    </iz:zalbe>
    <iz:zalbe>
        <iz:zalbaID>ID003</iz:zalbaID>
        <iz:sadrzaj>Садржај треће жалбе.</iz:sadrzaj>
    </iz:zalbe>
</iz:Izvestaj>
