=== gagi3/XML-2020/server/data/xsd/resenje-zalba-osnovana.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
    xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    elementFormDefault="qualified" 
    targetNamespace="http://www.pijz.rs/resenje-zalba-osnovana" 
    vc:minVersion="1.1"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
    xmlns:rzo="http://www.pijz.rs/resenje-zalba-osnovana">
    <xs:element name="ResenjeZalbaOsnovana">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="metadata"/>
                <xs:element name="trazilac" type="rzo:Osoba"/>
                <xs:element name="ustanova" type="rzo:Ustanova"/>
                <xs:element name="poverenik" type="rzo:Osoba"/>
                <xs:element name="datum_zahteva" type="xs:date"/>
                <xs:element name="dispozitiv">
                    <xs:complexType>
                        <xs:sequence minOccurs="1">
                            <xs:element name="stav">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="dokument">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="naziv">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:string">
                                                  <xs:minLength value="1"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                  </xs:element>
                                                  <xs:element name="zasticene_informacije">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element name="zasticena_informacija">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:string">
                                                  <xs:minLength value="2"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                  </xs:element>
                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="rok_obavestenja">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:int">
                                                  <xs:minInclusive value="0"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="redni_broj">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:int">
                                                <xs:minInclusive value="1"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="obrazlozenje">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="datum_izjave" type="xs:date"/>
                            <xs:element name="datum_postupka" type="xs:date"/>
                            <xs:element name="rok_postupka">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:minInclusive value="0"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="rok_zahteva">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:minInclusive value="0"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="tuzba">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="rok">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:int">
                                                  <xs:minInclusive value="0"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="taksa">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:double">
                                                  <xs:minInclusive value="0"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="broj">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="datum" type="xs:date"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="Osoba">
        <xs:sequence>
            <xs:element name="ime">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="2"/>
                        <xs:maxLength value="30"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="prezime">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="2"/>
                        <xs:maxLength value="30"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Ustanova">
        <xs:sequence>
            <xs:element name="naziv">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="2"/>
                        <xs:maxLength value="30"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="grad">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="2"/>
                        <xs:maxLength value="30"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="ulica">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="2"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="broj" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== gagi3/XML-2020/server/data/demo/rzo-instance3.xml
<?xml version="1.0" encoding="UTF-8"?>
<rzo:ResenjeZalbaOsnovana xmlns:rzo="http://www.pijz.rs/resenje-zalba-osnovana"
 xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
 xmlns:cmn="http://www.pijz.rs/common"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.pijz.rs/resenje-zalba-osnovana file:/D:/College/XML%202020/Project/XML-2020/server/data/xsd/resenje-zalba-osnovana.xsd" id="ID002" broj="broj0" datum="2006-05-04" datum_zahteva="2006-05-04" datum_zalbe="2006-05-04" datum_postupka="2006-05-04">
    <rzo:metadata>
        <cmn:meta property="property0" content="content0">meta0</cmn:meta>
        <cmn:meta property="property1" content="content1">meta1</cmn:meta>
    </rzo:metadata>
    <rzo:trazilac>
        <cmn:ime>ime0</cmn:ime>
        <cmn:prezime>prezime0</cmn:prezime>
        <cmn:adresa>
            <cmn:grad>grad0</cmn:grad>
            <cmn:ulica>ulica0</cmn:ulica>
            <cmn:broj>broj0</cmn:broj>
        </cmn:adresa>
    </rzo:trazilac>
    <rzo:poverenik>
        <cmn:ime>ime1</cmn:ime>
        <cmn:prezime>prezime1</cmn:prezime>
        <cmn:adresa>
            <cmn:grad>grad1</cmn:grad>
            <cmn:ulica>ulica1</cmn:ulica>
            <cmn:broj>broj1</cmn:broj>
        </cmn:adresa>
    </rzo:poverenik>
    <rzo:ustanova>
        <cmn:naziv>naziv0</cmn:naziv>
        <cmn:adresa>
            <cmn:grad>grad2</cmn:grad>
            <cmn:ulica>ulica2</cmn:ulica>
            <cmn:broj>broj2</cmn:broj>
        </cmn:adresa>
    </rzo:ustanova>
    <rzo:dispozitiv>
        <rzo:stav redni_broj="0">
            <rzo:dokument>
                <rzo:naziv>naziv0</rzo:naziv>
                <rzo:zasticena_informacija>zasticena_informacija0</rzo:zasticena_informacija>
                <rzo:zasticena_informacija>zasticena_informacija1</rzo:zasticena_informacija>
            </rzo:dokument>
            <rzo:rok_obavestenja>0</rzo:rok_obavestenja>
        </rzo:stav>
        <rzo:stav redni_broj="0">
            <rzo:dokument>
                <rzo:naziv>naziv1</rzo:naziv>
                <rzo:zasticena_informacija>zasticena_informacija2</rzo:zasticena_informacija>
                <rzo:zasticena_informacija>zasticena_informacija3</rzo:zasticena_informacija>
            </rzo:dokument>
            <rzo:rok_obavestenja>0</rzo:rok_obavestenja>
        </rzo:stav>
    </rzo:dispozitiv>
    <rzo:obrazlozenje>
        <rzo:paragraf>
            <rzo:rok_postupka>0</rzo:rok_postupka>
            <rzo:rok_zahteva>0</rzo:rok_zahteva>
        </rzo:paragraf>
        <rzo:paragraf>
            <rzo:rok_postupka>0</rzo:rok_postupka>
            <rzo:rok_zahteva>0</rzo:rok_zahteva>
        </rzo:paragraf>
        <rzo:tuzba>
            <cmn:rok>0</cmn:rok>
            <cmn:taksa>0</cmn:taksa>
        </rzo:tuzba>
    </rzo:obrazlozenje>
</rzo:ResenjeZalbaOsnovana>
